PhotoAppMVC.Web/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PhotoAppMVC.Application.Interfaces;
using PhotoAppMVC.Application.ViewModels;
using PhotoAppMVC.Application.ViewModels.Blog;
using PhotoAppMVC.Domain.Interface;
using PhotoAppMVC.Domain.Model;
using PhotoAppMVC.Infrastructure;
using Serilog;

namespace PhotoAppMVC.Web.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogService _blogService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly Context _context;

        public BlogController(IBlogService blogService, IWebHostEnvironment webHostEnvironment, Context context)
        {
            _blogService = blogService;
            _webHostEnvironment = webHostEnvironment;
            _context = context;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var model = _blogService.GetBlogForView();
            return View(model);
        }

        [HttpGet]
        public IActionResult AddBlog()
        {
            return View(new NewBlogVM());

        }
        [HttpPost]
        public IActionResult AddBlog(NewBlogVM blog, IFormFile file)
        {
            blog.PhotoPath = file.FileName;
            var id = _blogService.AddNewBlog(blog);
                return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditBlog(int id)
        {
            var blog = _blogService.GetBlogForEdit(id);
            return View(blog);
        }
        [HttpPost]
        public IActionResult EditBlog(NewBlogVM model)
        {
            if (ModelState.IsValid)
            {
                _blogService.UpdateBlog(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public IActionResult Delete(int id)
        {
            _blogService.DeleteBlog(id);
            return RedirectToAction("Index");
        }

    }
}

PhotoAppMVC.Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PhotoAppMVC.Application.Interfaces;
using PhotoAppMVC.Application.ViewModels;
using PhotoAppMVC.Application.ViewModels.Categories;
using PhotoAppMVC.Domain.Model;

namespace PhotoAppMVC.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoriesService _categoriesService;

        public CategoryController(ICategoriesService categoriesService)
        {
            _categoriesService = categoriesService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var model = _categoriesService.GetCategoryForView();
            return View(model);
        }

        //[HttpPost]
        //public IActionResult Index()
        //{
        //    var model = _categoriesService.GetCategoryForView();
        //    return View(model);
        //}
        [HttpGet]
        public IActionResult AddCategory()
        {
            return View(new NewCategoriesVM());

        }
        [HttpPost]
        public IActionResult AddCategory(NewCategoriesVM categories)
        {

            var id = _categoriesService.AddNewCategories(categories);
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult EditCategory(int id)
        {
            var cat = _categoriesService.GetCategoryForEdit(id);
            return View(cat);
        }

        [HttpPost]
        public IActionResult EditCategory(NewCategoriesVM model)
        {
            if (ModelState.IsValid)
            {
                _categoriesService.UpdateCategory(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult DeleteCategory(int id)
        {
            _categoriesService.DeleteCategory(id);
            return RedirectToAction("Index");
        }

    }
}

PhotoAppMVC.Web/Controllers/ConctactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PhotoAppMVC.Application.Interfaces;
using PhotoAppMVC.Application.ViewModels.Contact;

namespace PhotoAppMVC.Web.Controllers
{
    public class ConctactController : Controller
    {
        private readonly IContactService _contService;

        public ConctactController(IContactService contService)
        {
            _contService = contService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var model = _contService.GetAllContactsForList(10, 1, "");
            return View(model);
        }
        [HttpPost]
        public IActionResult Index(int pageSize, int? pageNo, string searchString)
        {
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }

            if (searchString is null)
            {
                searchString = String.Empty;
            }
            var model = _contService.GetAllContactsForList(pageSize, pageNo.Value, searchString);
            return View(model);
        }

        [HttpGet]
        public IActionResult AddNewMessage()
        {
            return View( new NewContactMessageVM());
        }
        [HttpPost]
        public IActionResult AddNewMessage(NewContactMessageVM contact)
        {
                var id = _contService.AddMessage(contact);
                return RedirectToAction("Index");

        }
        public IActionResult Contact_us()
        {
            return View();
        }

        public IActionResult ViewMessage(int id)
        {
           var contactModel = _contService.GetCustomerDetails(id);
            return View(contactModel);
        }

        public IActionResult Delete(int id)
        {
            _contService.DeleteMessage(id);
            return RedirectToAction("Index");
        }

        

    }
}

PhotoAppMVC.Web/Controllers/OfferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PhotoAppMVC.Application.Interfaces;
using PhotoAppMVC.Application.ViewModels.Offer;

namespace PhotoAppMVC.Web.Controllers
{
    public class OfferController : Controller
    {
        private readonly IOfferService _offerService;

        public OfferController(IOfferService offerService)
        {
            _offerService = offerService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var model = _offerService.GetOfferForView(8, 1, "");
            return View(model);
        }
        [HttpPost]
        public IActionResult Index(int pageSize, int? pageNo, string searchString)
        {
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }

            if (searchString is null)
            {
                searchString = String.Empty;
            }
            var model = _offerService.GetOfferForView(pageSize, pageNo.Value, searchString);
            return View(model);
        }


        [HttpGet]
        public IActionResult AddOffer()
        {

            return View(new NewOfferVM());


        }
        [HttpPost]
        public IActionResult AddOffer(NewOfferVM offer)
        {

            var id = _offerService.AddNewOffer(offer);

            return RedirectToAction("Index");


        }

        [HttpGet]
        public IActionResult EditOffer(int id)
        {
            var offer = _offerService.GetOfferForEdit(id);
            return View(offer);
        }

        [HttpPost]
        public IActionResult EditOffer(NewOfferVM model)
        {
            if (ModelState.IsValid)
            {
                _offerService.UpdateOffer(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult DeleteOffer(int id)
        {
            _offerService.DeleteOffer(id);
            return RedirectToAction("Index");

        }
    }
}

PhotoAppMVC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PhotoAppMVC.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/menu.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/about-me.css" />
</head>

    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 nav-menu">

                <div class="container ">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tu będzie <br/> 
                        Logo</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Offer" asp-action="Index">Oferta</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Portfolio" asp-action="Index">Portfolio</a>
                                <ul>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Photo" asp-action="Privacy">Zdjęcia ślubne</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Photo" asp-action="Privacy">Sesje narzeczeńskie</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Photo" asp-action="Privacy">Sesje indywidualne</a>
                                    </li>
                                </ul>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index"> Blog</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="AddBlog"> AddBlog</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index"> Kategorie</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Timetable" asp-action="Privacy">Terminarz</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Conctact" asp-action="Contact_us">O mnie</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Conctact" asp-action="AddNewMessage">Kontakt</a>
                            </li>
                        </ul>
                    </div>
                </div>

            </nav>

        </header>

<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - PhotoAppMVC.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
    </body>

</html>